<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-question.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 Απάντηση',
		'a_convert_to_c' => 'Μετατρέψτε αυτή την απάντηση σε σχόλιο',
		'a_convert_to_c_on' => 'Μετατρέψτε αυτή την απάντηση σε σχόλιο σε:',
		'a_convert_warn' => 'Προσοχή: Αυτή η αλλαγή δεν μπορεί να αναστραφεί.',
		'a_convert_warn_cs' => 'Προσοχή: Αυτή η αλλαγή δεν μπορεί να αναστραφεί και θα μετακινήσει το σχόλια της απάντησης.',
		'a_notify_email' => 'Αποστολή ηλεκτρονικού μηνύματος αν η απάντηση μου επιλεχθεί ή σχολιαστεί σε:',
		'a_notify_label' => 'Αποστολή ηλεκτρονικού μηνύματος αν η απάντηση μου επιλεχθεί ή σχολιαστεί',
		'a_notify_x_label' => 'Αποστολή ηλεκτρονικού μηνύματος (^) αν η απάντηση μου επιλεχθεί ή σχολιαστεί',
		'a_waiting_your_approval' => 'Αυτή η απάντηση περιμένει την έγκριση σας',
		'a_your_waiting_approval' => 'Η απάντηση σας θα ελεγχθεί και θα εγκριθεί σύντομα.',
		'add_answer_button' => 'Προσθήκη απάντησης',
		'add_comment_button' => 'Προσθήκη σχολίου',
		'add_q_favorites' => 'Προσθήκη ερώτησης στα αγαπημένα',
		'anon_name_label' => 'Το όνομα σας (προεραιτικό):',
		'answer_button' => 'απαντήστε',
		'answer_limit' => 'Ελήφθησαν πάρα πολλές απαντήσεις - παρακαλώ δοκιμάστε αργότερα',
		'answer_must_be_approved' => 'Ο λογαριασμός σας πρέπει να εγκριθεί πριν απαντήσετε κάποια ερώτηση.',
		'answer_must_confirm' => 'Παρακαλώ ^5επιβεβαιώστε την ηλεκτρονική σας διεύθυνση^6 για να απαντήσετε την ερώτηση.',
		'answer_must_login' => 'Παρακαλώ ^1συνδεθείτε^2 ή ^3εγγραφείτε^4 για να απαντήσετε την ερώτηση.',
		'answer_q_popup' => 'Απαντήστε την ερώτηση',
		'approve_a_popup' => 'Εγκρίνω την απάντηση',
		'approve_button' => 'εγκρίνω',
		'approve_c_popup' => 'Εγκρίνω το σχόλιο',
		'approve_q_popup' => 'Εγκρίνω την ερώτηση',
		'ask_button' => 'Ρωτήστε',
		'ask_follow_from_a' => 'Η ερώτηση σας θα συσχετιστεί με αυτή την απάντηση:',
		'ask_follow_title' => 'Δημιουργήστε μία σχετική ερώτηση',
		'ask_limit' => 'Ελήφθησαν πάρα πολλές ερωτήσεις - παρακαλώ δοκιμάστε αργότερα',
		'ask_must_be_approved' => 'Ο λογαριασμός σας πρέπει να εγκριθεί πριν δημιουργήσετε κάποια ερώτηση.',
		'ask_must_confirm' => 'Παρακαλώ ^5επιβεβαιώστε την ηλεκτρονική σας διεύθυνση^6 to ask a question.',
		'ask_must_login' => 'Παρακαλώ ^1συνδεθείτε^2 or ^3εγγραφείτε^4 to ask a question.',
		'ask_same_q' => 'Πριν συνεχίσετε, παρακαλώ ελέγξτε αν η ερώτηση σας έχει γίνει ήδη:',
		'ask_title' => 'Δημιουργία ερώτησης',
		'c_notify_email' => 'Να αποσταλεί ηλεκτρονικό μήνυμα σε αυτή την διεύθυνση αν προστεθεί σχόλιο μετά το δικό μου:',
		'c_notify_label' => 'Να αποσταλεί ηλεκτρονικό μήνυμα αν προστεθεί σχόλιο μετά το δικό μου',
		'c_notify_x_label' => 'Να αποσταλεί ηλεκτρονικό μήνυμα (^) αν προστεθεί σχόλιο μετά το δικό μου',
		'c_waiting_your_approval' => 'Αυτό το σχόλιο αναμένει την έγκριση σας',
		'c_your_waiting_approval' => 'Το σχόλιο σας θα ελεγχθεί και εγκριθεί σύντομα.',
		'category_ask_not_allowed' => 'Δεν έχετε δικαίωμα να δημιουργήσετε ερώτηση σε αυτή τη κατηγορία',
		'category_js_note' => 'Για να επιλέξετε κατηγορία, παρακαλώ ενεργοποιήστε την Javascript στον φυλλομετρητής',
		'category_required' => 'Παρακαλώ επιλέξτε μία κατηγορία',
		'claim_a_popup' => 'Ανάθεση της απάντησης στον λογαριασμό σου',
		'claim_button' => 'Εγώ το έγραψα',
		'claim_c_popup' => 'Ανάθεση του σχόλιου στον λογαριασμό σου',
		'claim_q_popup' => 'Ανάθεση της ερώτησης στον λογαριασμό σου',
		'clear_flags_button' => 'αφαίρεση των flags',
		'clear_flags_popup' => 'Αφαίρεση των flags από όλους τους χρήστες',
		'close_button' => 'κλείσιμο',
		'close_duplicate' => 'Η ερώτηση είναι επαναδιατύπωση κάποιας άλλης',
		'close_duplicate_error' => 'The duplicate question could not be found - please try entering the number from a different question URL, e.g. 123.',
		'close_form_button' => 'Κλείσιμο ερώτησης',
		'close_form_title' => 'Κλείσιμο ερώτησης',
		'close_original_note' => 'Μπορείτε επίσης να εισάγετε τον αριθμό της ερώτησης από το URL, πχ 123.',
		'close_original_title' => 'URL της αρχικής ερώτησης:',
		'close_q_popup' => 'Κλείσιμο της ερώτησης για περαιτέρω απαντήσεις',
		'close_reason_title' => 'Λόγος κλεισίματος της ερώτησης:',
		'closed_as_duplicate' => 'έκλεισε ως επαναδιατύπωση της:',
		'closed_with_note' => 'έκλεισε με την σημείωση:',
		'comment_a_popup' => 'Προσθήκη σχολίου στην απάντηση',
		'comment_button' => 'σχόλιο',
		'comment_limit' => 'Ελήφθησαν πάρα πολλά σχόλια - παρακαλώ δοκιμάστε αργότερα',
		'comment_must_be_approved' => 'Ο λογαριασμός σας πρέπει να εγκριθεί πριν σχολιάσετε κάποια ερώτηση.',
		'comment_must_confirm' => 'Παρακαλώ ^5επιβεβαιώστε την ηλεκτρονική σας διεύθυνση^6 για να προσθέσετε σχόλιο.',
		'comment_must_login' => 'Παρακαλώ ^1συνδεθείτε^2 ή ^3εγγραφείτε^4 για να προσθέσετε σχόλιο.',
		'comment_on_a' => 'Στην απάντηση: ',
		'comment_on_q' => 'Στην ερώτηση: ',
		'comment_q_popup' => 'Προσθήκη σχολίου στην ερώτηση',
		'delete_a_popup' => 'Οριστική διαγραφή απάντησης',
		'delete_button' => 'διαγραφή',
		'delete_c_popup' => 'Οριστική διαγραφή σχόλιου',
		'delete_q_popup' => 'Οριστική διαγραφή ερώτησης',
		'duplicate_content' => 'Η εκχώρηση σας φαίνεται να είναι επαναδιατύπωση άλλης.',
		'edit_a_popup' => 'Επεξεργασία απάντησης',
		'edit_a_title' => 'Επεξεργασία Απάντησης',
		'edit_button' => 'επεξεργασία',
		'edit_c_popup' => 'Επεξεργασία σχόλιου',
		'edit_c_title' => 'Επεξεργασία Σχόλιου',
		'edit_must_confirm' => 'Παρακαλώ ^5επιβεβαιώστε την ηλεκτρονική σας διεύθυνση^6 για να το επεξεργαστήτε.',
		'edit_must_login' => 'Παρακαλώ ^1συνδεθείτε^2 or ^3εγγραφείτε^4 για να το επεξεργαστήτε.',
		'edit_q_popup' => 'Επεξεργασία ερώτησης',
		'edit_q_title' => 'Επεξεργασία Ερώτησης',
		'example_tags' => 'Ετικέτες παράδειγμα: ',
		'flag_a_popup' => 'Μαρκάρετε αυτή την απάντηση ως spam ή ακατάλληλη',
		'flag_button' => 'flag',
		'flag_c_popup' => 'Μαρκάρετε αυτό το σχόλιο ως spam ή ακατάλληλο',
		'flag_hide_button' => 'μαρκάρετε και κρύψτε',
		'flag_limit' => 'Πάρα πολλές δημοσιεύσεις έγιναν flag - παρακαλώ δοκιμάστε αργότερα',
		'flag_must_confirm' => 'Παρακαλώ ^5επιβεβαιώστε την ηλεκτρονική σας διεύθυνση^6 για να καταγγείλετε δημοσιεύσεις.',
		'flag_must_login' => 'Παρακαλώ ^1συνδεθείτε^2 ή ^3εγγραφείτε^4 για να καταγγείλετε δημοσιεύσεις.',
		'flag_not_allowed' => 'Δεν επιτρέπετε το μαρκάρισμα εδώ',
		'flag_q_popup' => 'Μαρκάρετε αυτή την ερώτηση ως spam ή ακατάλληλη',
		'follow_a_popup' => 'Δημιουργήστε νέα ερώτηση σχετικά με αυτή την απάντηση',
		'follow_button' => 'Δημιουργήστε σχετική ερώτηση',
		'follows_a' => 'συσχετισμένη με μία απάντηση για:',
		'follows_q' => 'σχετικά με την ερώτηση:',
		'hide_a_popup' => 'Απόκρυψη απάντησης',
		'hide_button' => 'απόκρυψη',
		'hide_c_popup' => 'Απόκρυψη σχόλιου',
		'hide_q_popup' => 'Απόκρυψή ερώτησης',
		'matching_tags' => 'Ετικέτες που ταιριάζουν: ',
		'max_tags_x' => 'Επιτρέπονται μέχρι ^ ετικέτες',
		'min_tags_x' => 'Παρακαλώ προσθέστε τουλάχιστον ^ ετικέτες',
		'notify_email_note' => 'Privacy: Η ηλεκτρονική σας διεύθυνση θα χρησημοποιηθεί μόνο για την αποστολή αυτών των ειδοποιήσεων.',
		'q_category_label' => 'Κατηγορία:',
		'q_content_label' => 'Περισσότερες πληροφορίες για την ερώτηση:',
		'q_hidden_author' => 'Αυτή η ερώτηση έχει κρυφτεί από τον συγγραφέα της',
		'q_hidden_flagged' => 'Αυτή η ερώτηση έχει καταγγελθεί και κρυφτεί',
		'q_hidden_other' => 'Αυτή η ερώτηση έχει κρυφτεί',
		'q_notify_email' => 'Αποστολή ηλεκτρονικού μηνύματος σε αυτή την διεύθυνση αν η ερώτηση μου απαντηθεί ή σχολιαστεί:',
		'q_notify_label' => 'Αποστολή ηλεκτρονικού μηνύματος αν η ερώτηση μου απαντηθεί ή σχολιαστεί',
		'q_notify_x_label' => 'Αποστολή ηλεκτρονικού μηνύματος (^) αν η ερώτηση μου απαντηθεί ή σχολιαστεί',
		'q_tags_comma_label' => 'Ετικέτες - χρησιμοποιήστε κόμμα (,) ως διαχωριστικό:',
		'q_tags_label' => 'Ετικέτες - χρησιμοποιήστε παύλες για να ενώσετε λέξεις:',
		'q_title_label' => 'Η ερώτηση σε μία πρόταση:',
		'q_waiting_approval' => 'Η ερώτηση αναμένει έγκριση',
		'q_waiting_your_approval' => 'Η ερώτηση αναμένει την έγκριση σας',
		'q_your_waiting_approval' => 'Η ερώτηση σας θα ελεγχθεί και εγκριθεί σύντομα.',
		'recat_button' => 'επανακατηγοριοποίηση',
		'recat_popup' => 'Αλλαγή κατηγορίας της ερώτησης',
		'recat_q_title' => 'Επανακατηγοριοποιήση Ερώτησης',
		'reject_a_popup' => 'Απόρριψη της απάντησης',
		'reject_button' => 'απόρριψή',
		'reject_c_popup' => 'Απόρριψη του σχόλιου',
		'reject_q_popup' => 'Απόρριψη της ερώτησης',
		'remove_q_favorites' => 'Αφαίρεση ερώτησης από τα αγαπημένα',
		'reopen_button' => 'ξανανοίξτε',
		'reopen_q_popup' => 'Ξαναάνοιξε την ερώτηση',
		'reply_button' => 'απαντήστε',
		'reply_c_popup' => 'Απαντήστε σε αυτό το σχόλιο',
		'reshow_a_popup' => 'Ξαναδείξε την απάντηση',
		'reshow_button' => 'ξαναδείξτε',
		'reshow_c_popup' => 'Ξαναδείξε το σχόλιο',
		'reshow_q_popup' => 'Ξαναδείξε την ερώτηση',
		'retag_button' => 'retag',
		'retag_cat_popup' => 'Αλλάξτε την κατηγορία ή τις ετικέτες της ερώτησης',
		'retag_popup' => 'Αλλάξτε τις ετικέτες της ερώτησης',
		'retag_q_title' => 'Retag την ερώτηση',
		'save_silent_label' => 'Σώστε στα κρυφά (δεν εμφανίζεται ότι επεξεργάσθηκε)',
		'select_popup' => 'Κάντε κλικ για να την επιλέξετε ως καλύτερη απάντηση',
		'select_text' => 'Καλύτερη απάντηση',
		'show_1_comment' => 'Εμφάνιση ενός σχόλιου',
		'show_1_previous_comment' => 'Εμφάνιση προηγούμενου σχόλιου',
		'show_x_comments' => 'Εμφάνιση ^ σχολίων',
		'show_x_previous_comments' => 'Εμφάνιση ^ προηγούμενων σχολίων',
		'unflag_button' => 'unflag',
		'unflag_popup' => 'Αφαιρέστε το flag που προσθέσατε',
		'unselect_popup' => 'Κάντε κλικ για να αφαιρέσετε την επιλογή',
		'x_answers_title' => '^ Απαντήσεις',
		'your_answer_title' => 'Η απάντηση σας',
		'your_comment_a' => 'Το σχόλιο σας στην απάντηση:',
		'your_comment_q' => 'Το σχόλιο σας στην ερώτηση:',
		'your_comment_q' => 'Your comment on this question:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
