<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-main.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 απάντηση',
		'1_comment' => '1 σχόλιο',
		'1_day' => '1 ημέρα',
		'1_disliked' => '1 αρνητικό',
		'1_flag' => '1 flag',
		'1_hour' => '1 ώρα',
		'1_liked' => '1 θετικό',
		'1_minute' => '1 λεπτό',
		'1_month' => '1 μήνα',
		'1_point' => '1 πόντο',
		'1_question' => '1 ερώτηση',
		'1_second' => '1 δευτερόλεπτο',
		'1_tag' => '1 ετικέτα',
		'1_user' => '1 χρήστης',
		'1_view' => '1 προβολή',
		'1_vote' => '1 ψήφος',
		'1_week' => '1 εβδομάδα',
		'1_year' => '1 χρόνος',
		'add_category_x_favorites' => 'Πρόσθεσε την κατηγορία ^ στα αγαπημένα',
		'add_favorites' => 'Προσθήκη στα αγαπημένα',
		'add_tag_x_favorites' => 'Προσθήκη του tag ^ στα αγαπημένα',
		'all_categories' => 'Όλες οι κατηγορίες',
		'anonymous' => 'Ανώνυμος',
		'answer_edited' => 'η απάντηση επεξεργάσθηκε',
		'answer_reshown' => 'η απάντηση ξαναπροβλήθηκε',
		'answer_selected' => 'η απάντηση επιλέχθηκε',
		'answered' => 'απαντήθηκε',
		'answered_qs_in_x' => 'Πιο απαντημένες ερωτήσεις σε ^',
		'answered_qs_title' => 'Πιο απαντημένες ερωτήσεις',
		'asked' => 'ερωτήθηκε',
		'asked_related_q' => 'έγινε σχετική ερώτηση',
		'by_x' => 'από τον/την ^',
		'cancel_button' => 'Ακύρωση',
		'closed' => 'έκλεισε',
		'comment_edited' => 'το σχόλιο επεξεργάσθηκε',
		'comment_moved' => 'το σχόλιο διαγράφηκε',
		'comment_reshown' => 'το σχόλιο ξαναπροβλήθηκε',
		'commented' => 'σχολιάσθηκε',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^day ^month, ^year',
		'date_format_this_year' => '^day ^month',
		'date_month_1' => 'Ιαν',
		'date_month_2' => 'Φεβ',
		'date_month_3' => 'Μαρ',
		'date_month_4' => 'Απρ',
		'date_month_5' => 'Μαι',
		'date_month_6' => 'Ιουν',
		'date_month_7' => 'Ιουλ',
		'date_month_8' => 'Αυγ',
		'date_month_9' => 'Σεπ',
		'date_month_10' => 'Οκτ',
		'date_month_11' => 'Νοε',
		'date_month_12' => 'Δεκ',
		'date_year_digits' => 2, // 2 or 4
		'edited' => 'επεξεργάσθηκε',
		'email_error' => 'Εμφανίστηκε κάποιο λάθος κατά την αποστολή του email.',
		'field_required' => 'Παρακαλώ συμπληρώστε το πεδίο',
		'file_upload_limit_exceeded' => 'Το μέγεθος του αρχείου είναι μεγαλύτερο του επιτρεπτού',
		'general_error' => 'Παρουσιάστηκε σφάλμα στον εξυπηρετητή – παρακαλώ δοκιμάστε ξανά.',
		'hidden' => 'κρυφό',
		'highest_users' => 'Οι χρήστες με το μεγαλύτερο σκορ',
		'hot_qs_in_x' => 'Δημοφιλείς ερωτήσεις σε ^',
		'hot_qs_title' => 'Δημοφιλείς ερωτήσεις',
		'image_not_read' => 'Η εικόνα δεν μπορεί να αναγνωσθεί. Παρακαλώ ανεβάστε μία από: ^',
		'image_too_big_x_pc' => 'Η εικόνα είναι πολύ μεγάλη. Παρακαλώ σμικρύνεται την κατά ^% και ξαναπροσπαθήστε.',
		'in_category_x' => 'σε ^',
		'ip_address_x' => 'IP διευθύνσεις ^',
		'logged_in_x' => 'Γεια σου ^',
		'max_length_x' => 'Μέγιστο μήκος ^ χαρακτήρες',
		'max_upload_size_x' => 'Μέγιστο μέγεθος αρχείου ^',
		'me' => 'εμένα',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Παρακαλώ παρέχεται περισσότερες πληροφορίες - τουλάχιστον ^ χαρακτήρες',
		'moved' => 'μεταφέρθηκε',
		'nav_activity' => 'Όλες οι δραστηριότητες',
		'nav_admin' => 'Διαχείριση',
		'nav_ask' => 'Ρωτήστε',
		'nav_categories' => 'Κατηγορίες',
		'nav_feedback' => 'Αποστολή σχολίου',
		'nav_home' => 'Αρχική',
		'nav_hot' => 'Δημοφιλείς!',
		'nav_login' => 'Είσοδος',
		'nav_logout' => 'Αποσύνδεση',
		'nav_most_answers' => 'Περισσότερες απαντήσεις',
		'nav_most_recent' => 'Πρόσφατες',
		'nav_most_views' => 'Περισσότερες προβολές',
		'nav_most_votes' => 'Περισσότερες ψήφοι',
		'nav_no_answer' => 'Χωρίς απαντήσεις',
		'nav_no_selected_answer' => 'Χωρίς επιλεγμένη απάντηση',
		'nav_no_upvoted_answer' => 'Χωρίς ψήφο απάντηση',
		'nav_qa' => 'Ε&Α',
		'nav_qs' => 'Ερωτήσεις',
		'nav_register' => 'Εγγραφή',
		'nav_tags' => 'Ετικέτες',
		'nav_unanswered' => 'Αναπάντητες',
		'nav_updates' => 'Ενημερώσεις',
		'nav_users' => 'Χρήστες',
		'no_active_users' => 'Δεν βρέθηκαν ενεργοί χρήστες',
		'no_answers_found' => 'Δεν βρέθηκαν απαντήσεις',
		'no_answers_in_x' => 'Καμία απάντηση σε ^',
		'no_categories_found' => 'Δεν βρέθηκαν κατηγορίες',
		'no_category' => 'Καμία κατηγορία',
		'no_comments_found' => 'Δεν βρέθηκαν σχόλια',
		'no_comments_in_x' => 'Κανένα σχόλιο σε ^',
		'no_questions_found' => 'Δεν βρέθηκε καμία ερώτηση',
		'no_questions_in_x' => 'Καμία ερώτηση σε ^',
		'no_related_qs_title' => 'Δεν βρέθηκαν σχετικές ερωτήσεις',
		'no_results_for_x' => 'Δεν βρέθηκαν αποτελέσματα για ^',
		'no_tags_found' => 'Δεν βρέθηκαν ετικέτες',
		'no_una_questions_found' => 'Δεν βρέθηκαν αναπάντητες ερωτήσεις',
		'no_una_questions_in_x' => 'Δεν υπάρχουν αναπάντητες ερωτήσεις σε ^',
		'no_unselected_qs_found' => 'Δεν βρέθηκαν ερωτήσεις χωρίς επιλεγμένη απάντηση',
		'no_unupvoteda_qs_found' => 'Δεν βρέθηκαν ερωτήσεις χωρίς ψηφισμένη απάντηση',
		'page_label' => 'Σελίδα:',
		'page_next' => 'επόμενη',
		'page_not_found' => 'Η σελίδα δεν βρέθηκε',
		'page_prev' => 'προηγούμενη',
		'popular_tags' => 'Πιο δημοφιλείς ετικέτες',
		'questions_tagged_x' => 'Πρόσφατες ερωτήσεις με ετικέτα ^',
		'recategorized' => 'κατηγοριοποιήθηκε ξανά',
		'recent_activity_in_x' => 'Πρόσφατη δραστηριότητα σε ^',
		'recent_activity_title' => 'Πρόσφατη δραστηριότητα',
		'recent_as_in_x' => 'Πρόσφατα απαντημένες ερωτήσεις σε ^',
		'recent_as_title' => 'Πρόσφατα απαντημένες ερωτήσεις',
		'recent_cs_in_x' => 'Πρόσφατα σχολιασμένες ερωτήσεις σε ^',
		'recent_cs_title' => 'Πρόσφατα σχόλιασμένες ερωτήσεις',
		'recent_qs_as_in_x' => 'Πρόσφατες ερωτήσεις και απαντήσεις σε ^',
		'recent_qs_as_title' => 'Πρόσφατες ερωτήσεις και απαντήσεις',
		'recent_qs_in_x' => 'Πρόσφατες ερωτήσεις σε ^',
		'recent_qs_title' => 'Πρόσφατες ερωτήσεις',
		'related_qs_title' => 'Σχετικές ερωτήσεις',
		'remove_favorites' => 'Διαγραφή από τα αγαπημένα',
		'remove_x_favorites' => 'Διαγραφή ^ από τα αγαπημένα',
		'reopened' => 'ξανάνοιξε',
		'reshown' => 'ξαναπροβλήθηκε',
		'results_for_x' => 'Αποτελέσματα αναζήτησης για ^',
		'retagged' => 'retagged',
		'save_button' => 'Αποθήκευση αλλαγών',
		'search_button' => 'Αναζήτηση',
		'search_explanation' => 'Παρακαλώ συμπληρώστε το πεδίο και δοκιμάστε ξανά.',
		'search_title' => 'Αποτελέσματα αναζήτησης',
		'selected' => 'επιλέχθηκε',
		'send_button' => 'Αποστολή',
		'since_x' => 'από ^',
		'suggest_ask' => 'Κάντε μία ^1νέα ερώτηση^2.',
		'suggest_category_qs' => 'Για να δείτε περισσότερα, κάντε κλικ για όλες τις ^1ερωτήσεις σε αυτή τη κατηγορία^2.',
		'suggest_qs' => 'Για να δείτε περισσότερα, κάντε κλικ για την ^1πλήρη λίστα ερωτήσεων^2.',
		'suggest_qs_tags' => 'Για να δείτε περισσότερα, κάντε κλικ για την ^1πλήρη λίστα ερωτήσεων^2 ή ^3δημοφηλείς ετικέτες^4.',
		'to_x' => 'μέχρι ^',
		'unanswered_qs_in_x' => 'Ερωτήσεις χωρίς απάντηση σε ^',
		'unanswered_qs_title' => 'Πρόσφατες ερωτήσεις χωρίς απαντήσεις',
		'unselected_qs_in_x' => 'Ερωτήσεις χωρίς επιλεγμένη απάντηση σε ^',
		'unselected_qs_title' => 'Πρόσφατες ερωτήσεις χωρίς επιλεγμένη απάντηση',
		'unupvoteda_qs_in_x' => 'Ερωτήσεις χωρίς ψηφισμένη απάντηση σε ^',
		'unupvoteda_qs_title' => 'Πρόσφατες ερωτήσεις χωρίς ψηφισμένη απάντηση',
		'upload_limit' => 'Πάρα πολλές αναρτήσεις - παρακαλώ προσπαθήστε αργότερα',
		'view_q_must_be_approved' => 'Ο λογαριασμός σας πρέπει να εγκριθεί για να δείτε τις ερωτήσεις.',
		'view_q_must_confirm' => 'Παρακαλώ ^5επιβεβαιώστε την ηλεκτρονική σας διεύθυνση^6 για να δείτε σελίδες ερωτήσεων.',
		'view_q_must_login' => 'Παρακαλώ ^1συνδεθείτε^2 ή ^3εγγραφείτε^4 για να δείτε σελίδες ερωτήσεων.',
		'viewed_qs_in_x' => 'Ερωτήσεις με τις περισσότερες προβολές σε ^',
		'viewed_qs_title' => 'Ερωτήσεις με τις περισσότερες προβολές',
		'vote_disabled_approve' => 'Ο λογαριασμός πρέπει να εγκριθεί για να μπορείτε να ψηφίσετε',
		'vote_disabled_down' => 'Συγκεκριμένοι χρήστες μπορούν να ψηφίσουν αρνητικά',
		'vote_disabled_down_approve' => 'Ο λογαριασμός πρέπει να εγκριθεί για να μπορείτε να καταψηφίσετε',
		'vote_disabled_hidden_a' => 'Δεν μπορείτε να ψηφίσετε κρυμμένες απαντήσεις',
		'vote_disabled_hidden_q' => 'Δεν μπορείτε να ψηφίσετε κρυμμένες ερωτήσεις',
		'vote_disabled_level' => 'Η ψηφοφορία δεν επιτρέπεται σε όλους τους χρήστες',
		'vote_disabled_my_a' => 'Δεν μπορείτε να ψηφίσετε την απάντηση σας',
		'vote_disabled_my_q' => 'Δεν μπορείτε να ψηφίσετε την ερώτηση σας',
		'vote_disabled_q_page_only' => 'Παρακαλώ δείτε αυτή την ερώτηση για να ψηφίσετε',
		'vote_down_must_confirm' => 'Παρακαλώ ^5επιβεβαιώστε την ηλεκτρονική σας διεύθυνση^6 για να καταψηφίσετε.',
		'vote_down_popup' => 'Πατήστε για αρνητική',
		'vote_limit' => 'Πάρα πολλές ψήφοι - παρακαλώ δοκιμάστε αργότερα',
		'vote_must_confirm' => 'Παρακαλώ ^5επιβεβαιώστε την ηλεκτρονική σας διεύθυνση^6 για να ψηφίσετε',
		'vote_must_login' => 'Παρακαλώ ^1εισέλθετε^2 ή ^3εγγραφείτε^4 για να ψηφίσετε',
		'vote_not_allowed' => 'Η ψηφοφορία δεν επιτρέπεται',
		'vote_up_popup' => 'Πατήστε για θετική',
		'voted_down_popup' => 'Το έχετε καταψηφίσει - πατήστε για να αποσύρετε την ψήφο σας',
		'voted_qs_in_x' => 'Περισσότερο ψηφισμένες ερωτήσεις σε ^',
		'voted_qs_title' => 'Περισσότερο ψηφισμένες ερωτήσεις',
		'voted_up_popup' => 'Το έχετε υπερψηφίσει - πατήστε για να αποσύρετε την ψήφο σας',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => '^ πριν',
		'x_answers' => '^ απαντήσεις',
		'x_comments' => '^ σχόλια',
		'x_days' => '^ μέρες',
		'x_disliked' => '^ αρνητική',
		'x_flags' => '^ flags',
		'x_hours' => '^ ώρες',
		'x_liked' => '^ like',
		'x_minutes' => '^ λεπτά',
		'x_months' => '^ μήνες',
		'x_points' => '^ πόντοι',
		'x_questions' => '^ ερωτήσεις',
		'x_seconds' => '^ δευτερόλεπτα',
		'x_tags' => '^ ετικέτες',
		'x_users' => '^ χρήστες',
		'x_views' => '^ προβολές',
		'x_votes' => '^ ψήφοι',
		'x_weeks' => '^ εβδομάδες',
		'x_years' => '^ χρόνια',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
